name: publish Borderless Gaming


on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x" # SDK Version to use; x will use the latest version of the 7.0 channel
          include-prerelease: true

      # - name: Install bebopc
      #   shell: pwsh
      #   run: $version = '2.7.4'; $script = irm "https://bebop.sh"; & ([scriptblock]::Create($script)) -bebopcVersion $version

      - name: Install bebopc
        shell: pwsh
        run: |
          $version = '2.7.4'
          $script = irm "https://bebop.sh"
          & ([scriptblock]::Create($script)) -bebopcVersion $version
          
          $paths = ($env:PATH -split ';') + ([Environment]::GetEnvironmentVariable("PATH", "User") -split ';')
          $bebopPaths = $paths | Where-Object { $_ -match 'bebop' } | Select-Object -Unique
          foreach ($path in $bebopPaths) {
              Add-Content -Path $env:GITHUB_PATH -Value $path -Encoding utf8
          }
          $defaultPath = Join-Path $env:USERPROFILE ".bebop\bin"
          if (Test-Path $defaultPath) {
              Add-Content -Path $env:GITHUB_PATH -Value $defaultPath -Encoding utf8
          }

      - name: Build release
        shell: pwsh
        run: ./scripts/build-release.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: ./Installers/*.exe
